"""add company research fields

Revision ID: 9daad53484ab
Revises: cb0338633b06
Create Date: 2026-04-06 21:34:28.186184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9daad53484ab'
down_revision: Union[str, Sequence[str], None] = 'cb0338633b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funding_stage', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tech_stack_signals', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('culture_signals', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('glassdoor_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('growth_signals', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('red_flags', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('researched_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('researched_at')
        batch_op.drop_column('red_flags')
        batch_op.drop_column('growth_signals')
        batch_op.drop_column('glassdoor_rating')
        batch_op.drop_column('culture_signals')
        batch_op.drop_column('tech_stack_signals')
        batch_op.drop_column('funding_stage')

    # ### end Alembic commands ###
